### ISSUE TITLE
Deprecated structure in appinsts.yml

### ISSUE THREAD

**Issue by Mulinho** [mobiledgex/github-actions-sample#5]
The example presented below (from appinst.yml) does not work with `mobiledgex/deploy-app-action@v1.2.2`.
```
- appinst:
    key:
      cluster_inst_key:
        cluster_key:
          name: venky-test
        cloudlet_key:
          name: frankfurt-main
          organization: TDG
        organization: VenkyDev
```
This structure should work:
```
- appinst:
    key:
      cluster_inst_key:
        cluster_key:
          name: venky-test
          organization: VenkyDev
        cloudlet_key:
          name: frankfurt-main
          organization: TDG
```
